# Generated by Django 3.2.6 on 2021-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
